# train
data_path: "./data/tfrecord"
input_shape: [112, 112, 3]
backbone_type: "MobileNetV3Large"
batch_size: 32
epochs: 20

# predict
image_path: "./test/image/without_mask.png"
model_path: "./outputs/20220920_132501/model/model.h5"
using_tflite: False
tflite_path: "./outputs/20220920_132501/model/model.tflite"
